version: '3.8'  

services:  
  db:  
    image: mysql:5.7  
    container_name: mysql_rote42  
    environment:  
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: wordpress  
      MYSQL_USER: wordpressuser  
      MYSQL_PASSWORD: wordpresspass  
    ports:  
      - "3306:3306"  
    volumes:  
      - db_data:/var/lib/mysql  

  wordpress:  
    image: wordpress:latest  
    container_name: wordpress_rote42  
    environment:  
      WORDPRESS_DB_HOST: db:3306  
      WORDPRESS_DB_USER: wordpressuser  
      WORDPRESS_DB_PASSWORD: wordpresspass  
      WORDPRESS_DB_NAME: wordpress  
    ports:  
      - "8000:80"  
    volumes:  
      - wordpress_data:/var/www/html  
    depends_on:  
      - db  

volumes:  
  db_data:  
  wordpress_data:  
